# docker-compose.prod.yml

services:
  db:
    image: postgres:16-alpine
    container_name: meal_db_prod
    env_file: .env.prod
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    networks:
      - smart-meal-net-prod
    restart: unless-stopped

  backend:
    image: ${{ secrets.DOCKER_USERNAME }}/meal-backend:latest
    container_name: meal_backend_prod
    env_file: .env.prod
    volumes:
      - static_files_prod:/app/staticfiles
      - media_files_prod:/app/mediafiles
    depends_on:
      db:
        condition: service_healthy
    networks:
      - smart-meal-net-prod
    restart: unless-stopped

  frontend:
    image: ${{ secrets.DOCKER_USERNAME }}/meal-frontend:latest
    container_name: meal_frontend_prod
    depends_on:
      - backend
    networks:
      - smart-meal-net-prod
    restart: unless-stopped
      
  nginx:
    image: nginx:1.25-alpine
    container_name: meal_nginx_prod
    ports:
      - "8080:80"   
      - "8443:443"  
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro
      - static_files_prod:/app/staticfiles:ro
      - media_files_prod:/app/mediafiles:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
      - frontend
    networks:
      - smart-meal-net-prod
    restart: unless-stopped

networks:
  smart-meal-net-prod:
    driver: bridge

volumes:
  postgres_data_prod:
  static_files_prod:
  media_files_prod: