# docker-compose.yml

services:
  db:
    image: postgres:16-alpine
    container_name: meal_db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - smart-meal-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend:
    build: ./backend
    container_name: meal_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/src:/app
      - ./backend/mediafiles:/app/mediafiles 
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - smart-meal-net

  frontend:
    build: ./frontend
    container_name: meal_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - smart-meal-net
      
  nginx:
    build: ./nginx
    container_name: meal_nginx
    ports:
      - "80:80"
    volumes:
      - ./backend/mediafiles:/usr/share/nginx/html/media
    depends_on:
      - backend
      - frontend
    networks:
      - smart-meal-net

networks:
  smart-meal-net:
    driver: bridge

volumes:
  postgres_data:
